### PR TITLE
initial revision of contribution guidelines

### LINKED ISSUE #69: add CONTRIBUTING.md
xref https://github.com/mesosphere/mesos-dns/blob/master/CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by jdef**
- fixes #69

### CODE REVIEW

**Comment by jdef** [comment]
@spacejam PTAL

**Comment by spacejam** [comment]
I've heard a bit of negative feedback from people external to mesosphere about the guidelines used for eg mesos-dns.  I'm happy with this doc, but for a relatively large definition of "non-trivial".  I think we should only have to refer people to these in particularly egregious cases, otherwise we'll discourage contribution.

I'm happy with this being merged as-is, but we need to keep in mind that our interactions with contributors need to be framed around the goal of maximizing mutually beneficial future contribution.

**Comment by jdef** [comment]
The initial guidelines for mesos-dns were much heavier -- is that what
people were concerned about? If so that doesn't surprise me. This newer,
lighter form is much more forgiving.

Agreed w/ respect to maximizing future contribution.

**Comment by spacejam** [comment]
Yeah, I think it boiled down to someone wanting to help but us making it hard.

**Pull request merged**
